<a href="https://colab.research.google.com/github/arshiatehrani/MLP-Hardcode/blob/main/MLP.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import pandas as pd
from sklearn import preprocessing
from sklearn.datasets import load_breast_cancer
import matplotlib.pyplot as plt

In [ ]:
# Activation Functions

def Rand_Weights(size):
    _Rand = np.random.rand(size)
    return _Rand

def Sigmoid(_input):
    _Sigmoid = (2 / (1 + np.exp(-_input)) ) - 1
    return _Sigmoid

def tanh(_input):
    return np.tanh(_input)

def ReLU(_input):
    if _input < 0:
        return 0
    else:
        return 0.01 * _input
    
# Hypothesis Function    
def h(x, w, func, has_bias=False):
  if has_bias == True:
    x = np.concatenate( (x, -np.ones((x.shape[0],1)) ) , axis=1)

  if func == 'sigmoid':
    return Sigmoid(np.dot(x, w))
  elif func == 'tanh':
    return tanh(np.dot(x, w))
  elif func == 'ReLU':
    return ReLU(np.dot(x, w))
  else:
    return -1

def w(N_input, N_neurons=1, has_bias=False):
  if has_bias == True:
    N_input+=1
    
  rand_w = np.random.rand(N_input, N_neurons)
  return rand_w

#Dataset

In [ ]:
# Loading ds
ds = load_breast_cancer()
Feature = ds.feature_names
x = ds.data
y = ds.target
ds = pd.DataFrame(data=x, columns=Feature)
ds["target"] = y

# Converting to ".csv"
ds.to_csv("dataset.csv", index=False)
ds = pd.read_csv("dataset.csv")
ds.head()


mean radius  mean texture  mean perimeter  mean area  mean smoothness  \
0        17.99         10.38          122.80     1001.0          0.11840   
1        20.57         17.77          132.90     1326.0          0.08474   
2        19.69         21.25          130.00     1203.0          0.10960   
3        11.42         20.38           77.58      386.1          0.14250   
4        20.29         14.34          135.10     1297.0          0.10030   

   mean compactness  mean concavity  mean concave points  mean symmetry  \
0           0.27760          0.3001              0.14710         0.2419   
1           0.07864          0.0869              0.07017         0.1812   
2           0.15990          0.1974              0.12790         0.2069   
3           0.28390          0.2414              0.10520         0.2597   
4           0.13280          0.1980              0.10430         0.1809   

   mean fractal dimension  ...  worst texture  worst perimeter  worst area  \
0                 0.07871  ...          17.33           184.60      2019.0   
1                 0.05667  ...          23.41           158.80      1956.0   
2                 0.05999  ...          25.53           152.50      1709.0   
3                 0.09744  ...          26.50            98.87       567.7   
4                 0.05883  ...          16.67           152.20      1575.0   

   worst smoothness  worst compactness  worst concavity  worst concave points  \
0            0.1622             0.6656           0.7119                0.2654   
1            0.1238             0.1866           0.2416                0.1860   
2            0.1444             0.4245           0.4504                0.2430   
3            0.2098             0.8663           0.6869                0.2575   
4            0.1374             0.2050           0.4000                0.1625   

   worst symmetry  worst fractal dimension  target  
0          0.4601                  0.11890       0  
1          0.2750                  0.08902       0  
2          0.3613                  0.08758       0  
3          0.6638                  0.17300       0  
4          0.2364                  0.07678       0  

[5 rows x 31 columns]

In [ ]:
ds.describe()

mean radius  mean texture  mean perimeter    mean area  \
count   569.000000    569.000000      569.000000   569.000000   
mean     14.127292     19.289649       91.969033   654.889104   
std       3.524049      4.301036       24.298981   351.914129   
min       6.981000      9.710000       43.790000   143.500000   
25%      11.700000     16.170000       75.170000   420.300000   
50%      13.370000     18.840000       86.240000   551.100000   
75%      15.780000     21.800000      104.100000   782.700000   
max      28.110000     39.280000      188.500000  2501.000000   

       mean smoothness  mean compactness  mean concavity  mean concave points  \
count       569.000000        569.000000      569.000000           569.000000   
mean          0.096360          0.104341        0.088799             0.048919   
std           0.014064          0.052813        0.079720             0.038803   
min           0.052630          0.019380        0.000000             0.000000   
25%           0.086370          0.064920        0.029560             0.020310   
50%           0.095870          0.092630        0.061540             0.033500   
75%           0.105300          0.130400        0.130700             0.074000   
max           0.163400          0.345400        0.426800             0.201200   

       mean symmetry  mean fractal dimension  ...  worst texture  \
count     569.000000              569.000000  ...     569.000000   
mean        0.181162                0.062798  ...      25.677223   
std         0.027414                0.007060  ...       6.146258   
min         0.106000                0.049960  ...      12.020000   
25%         0.161900                0.057700  ...      21.080000   
50%         0.179200                0.061540  ...      25.410000   
75%         0.195700                0.066120  ...      29.720000   
max         0.304000                0.097440  ...      49.540000   

       worst perimeter   worst area  worst smoothness  worst compactness  \
count       569.000000   569.000000        569.000000         569.000000   
mean        107.261213   880.583128          0.132369           0.254265   
std          33.602542   569.356993          0.022832           0.157336   
min          50.410000   185.200000          0.071170           0.027290   
25%          84.110000   515.300000          0.116600           0.147200   
50%          97.660000   686.500000          0.131300           0.211900   
75%         125.400000  1084.000000          0.146000           0.339100   
max         251.200000  4254.000000          0.222600           1.058000   

       worst concavity  worst concave points  worst symmetry  \
count       569.000000            569.000000      569.000000   
mean          0.272188              0.114606        0.290076   
std           0.208624              0.065732        0.061867   
min           0.000000              0.000000        0.156500   
25%           0.114500              0.064930        0.250400   
50%           0.226700              0.099930        0.282200   
75%           0.382900              0.161400        0.317900   
max           1.252000              0.291000        0.663800   

       worst fractal dimension      target  
count               569.000000  569.000000  
mean                  0.083946    0.627417  
std                   0.018061    0.483918  
min                   0.055040    0.000000  
25%                   0.071460    0.000000  
50%                   0.080040    1.000000  
75%                   0.092080    1.000000  
max                   0.207500    1.000000  

[8 rows x 31 columns]

##Shuffling

In [ ]:
ds = ds.sample(frac=1.).reset_index(drop=True)
ds.head()

mean radius  mean texture  mean perimeter  mean area  mean smoothness  \
0       13.450         18.30           86.60      555.1          0.10220   
1       11.310         19.04           71.80      394.1          0.08139   
2       10.050         17.53           64.41      310.8          0.10070   
3        8.671         14.45           54.42      227.2          0.09138   
4       12.320         12.39           78.85      464.1          0.10280   

   mean compactness  mean concavity  mean concave points  mean symmetry  \
0           0.08165         0.03974              0.02780         0.1638   
1           0.04701         0.03709              0.02230         0.1516   
2           0.07326         0.02511              0.01775         0.1890   
3           0.04276         0.00000              0.00000         0.1722   
4           0.06981         0.03987              0.03700         0.1959   

   mean fractal dimension  ...  worst texture  worst perimeter  worst area  \
0                 0.05710  ...          25.94            97.59       699.4   
1                 0.05667  ...          23.84            78.00       466.7   
2                 0.06331  ...          26.84            71.98       384.0   
3                 0.06724  ...          17.04            58.36       259.2   
4                 0.05955  ...          15.64            86.97       549.1   

   worst smoothness  worst compactness  worst concavity  worst concave points  \
0            0.1339            0.17510           0.1381               0.07911   
1            0.1290            0.09148           0.1444               0.06961   
2            0.1402            0.14020           0.1055               0.06499   
3            0.1162            0.07057           0.0000               0.00000   
4            0.1385            0.12660           0.1242               0.09391   

   worst symmetry  worst fractal dimension  target  
0          0.2678                  0.06603       1  
1          0.2400                  0.06641       1  
2          0.2894                  0.07664       1  
3          0.2592                  0.07848       1  
4          0.2827                  0.06771       1  

[5 rows x 31 columns]

## Splitting data into "train" and "test" parts

In [ ]:
train = ds.sample(frac=0.8).reset_index(drop=True)
test = ds.drop(index=train.index).reset_index(drop=True)
# train = np.array(train)
# test = np.array(test)
print(f"{type(ds)}\n")
print(f"train shape:\n{train.shape}\n{type(train)}\n\n")
print(f"test shape:\n{test.shape}\n{type(test)}")

<class 'pandas.core.frame.DataFrame'>

train shape:
(455, 31)
<class 'pandas.core.frame.DataFrame'>


test shape:
(114, 31)
<class 'pandas.core.frame.DataFrame'>


##Extracting x and y

In [ ]:
x_train = train.drop(columns=['target']) # Training Data
# x_train = np.array(x_train)
x_train_count = len(x_train)
print(x_train_count)

y_train = train['target'] # Target Output
# y_train = np.array(y_train)

x_test = test.drop(columns=['target'])
# x_test = np.array(x_test)

y_test = test['target']
# y_test = np.array(y_test)

print(f"x_train shape:\n{x_train.shape}\n{type(x_train)}\n\n")
print(f"y_train shape:\n{y_train.shape}\n{type(y_train)}")

455
x_train shape:
(455, 30)
<class 'pandas.core.frame.DataFrame'>


y_train shape:
(455,)
<class 'pandas.core.series.Series'>


##Normalization

In [ ]:
mean = x_train.mean()
std = x_train.std()

x_train_n = (x_train - mean) / std
x_test_n = (x_test - mean) / std

In [ ]:
print(f"x_train_n shape:\n{x_train_n.shape}\n{type(x_train_n)}\n\n")
# x_train_n.describe()

x_train_n shape:
(455, 30)
<class 'pandas.core.frame.DataFrame'>




Converting to np.array for algorythm

In [ ]:
x_train = np.array(x_train)
y_train = np.array(y_train)
x_test = np.array(x_test)
y_test = np.array(y_test)
x_train_n = np.array(x_train_n)
x_test_n = np.array(x_test_n)

# For (455, ) to make it (455, 1) for good indexing
y_train = np.reshape(y_train, (len(y_train), 1))
y_train.shape
# print(len(y_train))
# print(y_train)

(455, 1)

#Training

In [ ]:
# Hyper_params

# w1 = Rand_Weights(x_train_n.shape[1])
# w2 = Rand_Weights(x_train_n.shape[1])
h_neuron_num = 4
w1 = w(x_train_n.shape[1], h_neuron_num, True)

print(f"w1_shape:\n{w1.shape}\nw1 =\n{w1}\n")
learning_rate = 0.1
E_max = 1e6
E = 0
epoch_count = 1
layer_count = 2

w1_shape:
(31, 4)
w1 =
[[0.6627763  0.88305818 0.94597077 0.71210819]
 [0.03647245 0.42173314 0.41199616 0.20833268]
 [0.85939355 0.52559901 0.27526081 0.46665891]
 [0.50342131 0.16348066 0.1576372  0.78981284]
 [0.16075535 0.15514723 0.5799541  0.63558485]
 [0.27174388 0.97071987 0.5597018  0.62400718]
 [0.37130277 0.72955375 0.07044598 0.4721989 ]
 [0.49226023 0.64134577 0.36115274 0.49533292]
 [0.83886834 0.79585593 0.00617149 0.75897029]
 [0.63865497 0.34993066 0.59166996 0.52703379]
 [0.00972903 0.75169513 0.58544665 0.19105425]
 [0.53781291 0.32211786 0.88393052 0.81098697]
 [0.74535991 0.40077293 0.20455011 0.85938122]
 [0.41623282 0.92961584 0.53494776 0.04536556]
 [0.05308058 0.11260409 0.75572335 0.18894273]
 [0.89014604 0.62336505 0.64472533 0.84104915]
 [0.40927173 0.74890047 0.1660132  0.13921812]
 [0.50546498 0.03203743 0.30660958 0.66606372]
 [0.98639505 0.37304779 0.82031093 0.14263359]
 [0.17051487 0.72993867 0.12249144 0.46835207]
 [0.91684155 0.41445821 0.14707282 0.

##Feedforward operation

###1st layer

In [ ]:
print(f"x_train_n shape:\n{x_train_n.shape}\n{type(x_train_n)}\n")
print(f"w1_shape:\n{w1.shape}\n")

# The output of 1st layer
z = h(x_train_n, w1, "sigmoid", True)
print(f"z_shape:\n{z.shape}\nz =\n{z}\n")

x_train_n shape:
(455, 30)
<class 'numpy.ndarray'>

w1_shape:
(31, 4)

z_shape:
(455, 4)
z =
[[ 0.99999996  1.          0.9999958   1.        ]
 [-0.9999391  -0.99994412 -0.9999106  -0.99990856]
 [-0.99953272 -0.99960373 -0.99792297 -0.99963323]
 ...
 [-0.9938248  -0.99815396 -0.9887496  -0.99703941]
 [-0.99991537 -0.99993512 -0.99934832 -0.99990914]
 [ 0.92158369  0.93191766  0.61317775  0.89926084]]



### Output layer

In [ ]:
print(f"z shape:\n{z.shape}\n{type(z)}\n")
# 2nd layer weights

o_neuron_num = 1
w2 = w(z.shape[1], o_neuron_num, True)
print(f"w2_shape:\n{w2.shape}\nw2 =\n{w2}\n")

# The output of 2nd layer
o = h(z, w2, "sigmoid", True)
print(f"o_shape:\n{o.shape}\no =\n{z}\n")

z shape:
(455, 4)
<class 'numpy.ndarray'>

w2_shape:
(5, 1)
w2 =
[[0.27024132]
 [0.31636497]
 [0.78555411]
 [0.96000066]
 [0.81896715]]

o_shape:
(455, 1)
o =
[[ 0.99999996  1.          0.9999958   1.        ]
 [-0.9999391  -0.99994412 -0.9999106  -0.99990856]
 [-0.99953272 -0.99960373 -0.99792297 -0.99963323]
 ...
 [-0.9938248  -0.99815396 -0.9887496  -0.99703941]
 [-0.99991537 -0.99993512 -0.99934832 -0.99990914]
 [ 0.92158369  0.93191766  0.61317775  0.89926084]]



##Backward Propagation

In [ ]:
# Weights
# Previous sections in general form
mse = []
layer_weights = []
rond_weights = []
layer_outputs = []
layer_neuron_num = [1, 1]
for epoch in range(epoch_count):
  E = 0
  for layer in range(layer_count):
    W = w(x_train_n.shape[1], layer_neuron_num[layer], True)
    O = h(x_train_n, W, "sigmoid", True)
    layer_weights.append(W)
    layer_outputs.append(O)

  E += 0.5 * (y_train[0] - layer_outputs[layer_count - 1])**2

# Backward Propagation
  # Output layer error
  delta_o = 0.5 * (y_train[0] - layer_outputs[layer_count - 1]) * (np.subtract(1, layer_outputs[layer_count - 1]**2 ))
  # for layer in range(layer_count):
  #   delta_y = 0.5 * (np.subtract(1, layer_outputs[layer]**2 )) * np.multiply(delta_o, layer_weights[layer]) 




    
    
# print(layer_outputs[layer_count - 1].shape)
print(y_train.shape)
print(type(y_train))
print(type(layer_outputs[layer_count - 1]))
print(E.shape)
print(type(E))
print(E)

In [ ]:
# np.subtract(1, np.eye(3, 3))
# A = np.subtract(1, layer_outputs[1])
# print(f"layer_outputs: {layer_outputs[1]}")
# print(f"A: {A}")
np.multiply(delta_o, layer_weights[0])

ValueError: ignored